Multi Environment Base Pipeline
satyamdudhat/Terragrunt-Interhsip pull request #12
Opened 2024-06-03 13:01 UTC by satyamdudhat

2024-06-04 06:26 UTC, Dharmik-Mashru requested changes

2024-06-04 06:26 UTC, th-dharmikmashru commented on .github/actions/ecr_push_image_dev/action.yml
> +    - name: Check ECR Repository
No need to check if repository exists.

2024-06-04 06:26 UTC, th-dharmikmashru commented on .github/actions/ecr_push_image_dev/action.yml
> +    - name: Push Image in ECR
image push can be handled in workflow itself, no need to use composite action here.

2024-06-04 06:26 UTC, th-dharmikmashru commented on .github/workflows/Dev_push.yml
> +    push:
- 2 space indentations should be used and it should be consistent across the workflows and actions.
- Adding pull request jobs for code build and terraform plan can help us verify the plan and build before merge.

2024-06-04 06:26 UTC, th-dharmikmashru commented on .github/workflows/Dev_push.yml
> +            run: bash infrastructure/scripts/aws_configuration.sh
use composite action here

2024-06-04 06:26 UTC, th-dharmikmashru commented on .github/workflows/Dev_push.yml
> +            run: |
use composite action here

2024-06-04 06:26 UTC, th-dharmikmashru commented on .github/actions/aws_terragrunt_configuration/action.yml
> +    - name: Configuration AWS
create different composite actions for aws configuration and tf and tg configuration.

2024-06-04 06:26 UTC, Dharmik-Mashru commented on .github/workflows/Dev_push.yml
> +          - name: ECR Repo Code
this step is not needed.

2024-06-04 06:26 UTC, Dharmik-Mashru commented on .github/workflows/Dev_push.yml
> +            run: |
- you should create a make target for this command
- use `|` only when you need to run multiple commands in same step

2024-06-04 06:26 UTC, Dharmik-Mashru commented on .github/workflows/Dev_push.yml
> +          # - name: Terragrunt apply Configuration
why is this commented?

2024-06-04 06:26 UTC, Dharmik-Mashru commented on .github/workflows/Prod_push.yml
same changes required as dev workflow

2024-06-04 06:26 UTC, Dharmik-Mashru commented on Makefile
> +prefix=project-dev
env var names should be in upper case

2024-06-04 06:26 UTC, Dharmik-Mashru commented on Makefile
> +destroy-ci:
this target is not required

2024-06-04 06:26 UTC, Dharmik-Mashru commented on Makefile
> +ecr-repo:
this target is not required

2024-06-04 06:26 UTC, Dharmik-Mashru commented on infrastructure/modules/Api_Gateway/variable.tf
reduce unnecessary spacing and do formatting.

2024-06-04 06:26 UTC, Dharmik-Mashru commented on infrastructure/scripts/ecr_rpo_check_dev.sh
this script is not required.

2024-06-04 06:26 UTC, Dharmik-Mashru commented on infrastructure/scripts/ecr_rpo_check_prod.sh
this script is not required.

2024-06-04 06:26 UTC, Dharmik-Mashru commented on infrastructure/scripts/image_push_code_prod.sh
environments should be handled within a single script, rather than creating different scripts for it.

2024-06-06 06:31 UTC, Dharmik-Mashru approved these changes

2024-06-06 07:08 UTC, piyushsonigra requested changes

2024-06-06 07:08 UTC, piyushsonigra commented on .github/workflows/dev_pull_push.yml
> +          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
why do we need account id for aws access setup?

2024-06-06 07:23 UTC, piyushsonigra approved these changes

2024-06-06 08:59 UTC, merged